name: mi_card
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - images/dylan.jpg


  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf


  - family: Ubuntu
    fonts:
    - asset:  fonts/Ubuntu-Medium.ttf

  - family: Simonetta
    fonts:
    - asset:
#              fonts/Simonetta-Regular.ttf
               fonts/Simonetta-Italic.ttf
#               fonts/Simonetta-BlackItalic.ttf
#               fonts/Simonetta-Black.ttf




